### ISSUE TITLE
IDE can't recognize module including webpack alias  

### ISSUE THREAD

**Issue by parkhojeong** [falsy/react-with-clean-architecture#75]
webstorm version: 2022.02

in my IDE, it cannot find module including alias of webpack or babel.
how do you set up with this problem?

![image](https://user-images.githubusercontent.com/34734102/156886021-d8784f1d-149c-43d6-90d5-b3924946fb40.png)

i tried below setting. it also doesn't work by preference setting

![image](https://user-images.githubusercontent.com/34734102/156886286-d0492023-fc5b-4510-9577-1415f2a6771e.png)

i think one solution is that put webpack.config file in root directory like below image
in web development, `src/web/di/`, in mobile development `src/mobile/di` 

![image](https://user-images.githubusercontent.com/34734102/156886561-fd0ff417-4d35-49bf-8e92-23ee9a765ddd.png)

between mobile babel and web webpack, are you switch setting by target environment between mobile and web?

**Comment by falsy** [comment]
@parkhojeong 
First of all, sorry for the late reply to your question.

As you kindly wrote, we have confirmed that there is a problem with the above alias.
thank you

It would be nice to find a way to solve the above problem, but
Currently, the above project is preparing to change to a MonoRepo configuration.
Perhaps after the change we will be able to respond to the above issues as well.

We will deploy the code of the changed idea as soon as possible.

Thanks again for your interest in this project and for leaving a problem.
